//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ou_UserInfo
    {
        public int uId { get; set; }
        public int uDepId { get; set; }
        public string uLoginName { get; set; }
        public string uPwd { get; set; }
        public bool uGender { get; set; }
        public string uPost { get; set; }
        public string uRemark { get; set; }
        public bool uIsDel { get; set; }
        public System.DateTime uAddTime { get; set; }
    }
}
